##### run with all profiles, doesn't specify supported-features 
#####
##### go test ./conformance -v -timeout 30m -run TestConformance -args --gateway-class=conformance \
##### --organization=RedHat --project=OpenShift --url="url" --version=v4.19  --contact="Contact" \
##### --conformance-profiles="GATEWAY-HTTP,GATEWAY-GRPC,GATEWAY-TLS,MESH-HTTP,MESH-GRPC" --report-output=./conformance-profile.yaml
#####

apiVersion: gateway.networking.k8s.io/v1
date: "2025-03-21T13:02:20+08:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.2.1
implementation:
  contact:
  - Contact
  organization: RedHat
  project: OpenShift
  url: url
  version: v4.19
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 1
      Skipped: 0
  name: MESH-GRPC
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 2
      Skipped: 0
  name: MESH-HTTP
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 12
      Skipped: 0
  name: GATEWAY-GRPC
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 33
      Skipped: 0
  name: GATEWAY-HTTP
  summary: Core tests succeeded.
- core:
    failedTests:
    - TLSRouteInvalidReferenceGrant
    - TLSRouteSimpleSameNamespace
    result: failure
    statistics:
      Failed: 2
      Passed: 9
      Skipped: 0
  name: GATEWAY-TLS
  summary: Core tests failed with 2 test failures.
