apiVersion: externaldns.olm.openshift.io/v1alpha1
kind: ExternalDNS
metadata:
  name: sample-aws
spec:
  provider:
    type: AWS
  zones:
  - "xxxxx"
  source:
    type: Service
    service:
      serviceType:
      - LoadBalancer
      - ClusterIP
    labelFilter:
      matchLabels:
        external-dns.mydomain.org/publish: "yes"
    fqdnTemplate:
    - "{{.Name}}.hongli-aws.qe.devcluster.openshift.com"
